//! Persona schema surface.
//!
//! `daemon` is the schema-emitted daemon shell (argv parsing, async
//! task-backed listener binding, the decode -> dispatch -> encode spine, and
//! the `ExitReport` entry) generated by schema-rust's daemon emitter from
//! the [`NexusDaemonShape`](../../build.rs) in `build.rs`. `reports` carries the
//! hand-written NOTA projection records the command-line surface renders.

pub mod daemon;
mod reports;

pub use reports::*;
